#
# Layer:  meta-ota
# Path:   meta-home-gateway/meta-ota
#

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "home-gateway-ota"
BBFILE_PATTERN_home-gateway-ota = "^${LAYERDIR}/"
BBFILE_PRIORITY_home-gateway-ota = "10"

# Layer dependencies:
LAYERDEPENDS_home-gateway-ota     = "core swupdate home-gateway-bsp"
LAYERSERIES_COMPAT_home-gateway-ota = "kirkstone"
