# Layer:  meta-bsp
# Path:   meta-home-gateway/meta-bsp

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "home-gateway-bsp"
BBFILE_PATTERN_home-gateway-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_home-gateway-bsp = "6"

LAYERDEPENDS_home-gateway-bsp     = "core"
LAYERSERIES_COMPAT_home-gateway-bsp = "kirkstone"
